export interface Recycler{
	id:any;
	name:string;
	lastName:string;
	createdAt:any;
	phone:string;
	image:any;
	gender:any;
	yearBirth:number;
	yearStartRecycling:number;
	date:any;
	material:any;
	recyclingFor:any;
	favoritiesUser:any;
	idUser:string;
	latitude:any;
	longitude:any;
	status:string;
	totalReceives:number;
}